# Generated by Django 3.2.9 on 2021-11-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_courseuser_videouser_worduser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worduser',
            old_name='Word',
            new_name='word',
        ),
    ]
