# Generated by Django 3.2.9 on 2021-11-10 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_word_worduser_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='course',
        ),
    ]
