# Generated by Django 3.2.9 on 2021-11-11 09:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_rename_video_video_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseuser',
            unique_together={('user', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='videouser',
            unique_together={('user', 'video')},
        ),
        migrations.AlterUniqueTogether(
            name='worduser',
            unique_together={('user', 'word')},
        ),
    ]
