# Generated by Django 3.2.9 on 2021-11-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211111_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='worduser',
            name='status',
            field=models.CharField(choices=[('learned', 'Learned'), ('not-learned', 'Not Learned')], default='not-learned', max_length=20),
        ),
    ]
