# Generated by Django 3.2.9 on 2021-11-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_video_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
    ]
