# Generated by Django 3.2.9 on 2021-12-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='core.video'),
        ),
    ]
