# Generated by Django 3.2.9 on 2021-12-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_word_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='type',
            field=models.CharField(choices=[('type-one', 'Type One'), ('type-two', 'Type Two'), ('type-three', 'Type Three'), ('type-four', 'Type Four')], default='type-one', max_length=20),
        ),
    ]
