WORD_USER_STATUS_LEARNED = 'learned'
WORD_USER_STATUS_NOT_LEARNED = 'not-learned'

WORD_USER_STATUS_CHOICES = (
    (WORD_USER_STATUS_LEARNED, 'Learned'),
    (WORD_USER_STATUS_NOT_LEARNED, 'Not Learned'),
)
